analysis_name: "DefaultAnalysis"

# ~~~~~~~~~~ Assembly.smk ~~~~~~~~~~ #
# ~ Input ~ #
test_fqs: "test_fqs"
raw_fqs: "raw_fqs"
raw_fqs_ext: "fastq.gz"

# ~ Program Options ~ #
fastqc_out: "qc/FastQC"
bbmerge_out: "filtered_reads"
metaspades_out: "assembly/metaspades"
megahit_out: "assembly/megahit"

# ~ Program Versions ~ #
# Placeholder, not sure how I want this to look

# ~~~~~~~~~~ Annotate.smk ~~~~~~~~~~ #
# ~ Input ~ #
raw_sequence: "All-Assemblies-Spades"
raw_sequence_ext: "fasta"
verified_sequence: "Verified-Assemblies-Spades"
anvio_contig_db: "ContigDBs"
annotation_sources: "CAZyme,COG20_CATEGORY,COG20_FUNCTION,COG20_PATHWAY,KEGG_Class,KEGG_Module,KOfam,Pfam"
# ~ Program Options ~ #


# Alignment.smk
assembly: "AssembledContigs"
assembly_extension: "fasta"
#fastqs: "raw_fastqs"
fq_extension: "fastq"
clean_assembly: "CleanAssembledContigs"
bins: "All-Bins"
clean_contigs: ""
contig_extension: "fasta"
contigdb: "ContigDBs"

# File Specifications
fastas: "../tests/results/fasta_files"
fastqs: "raw_fastqs"
#extension: "fasta"  # Double-booked in Annotate an Align

# Program options

kaiju: "taxonomy/kaiju"
kraken2: "taxonomy/kraken2"
kraken2_db: "/depot/lindems/data/Databases/Kraken/database"


# Output paths
verified_contigs: "../tests/results/fasta_files_verified"
filtered_contigs: "../tests/results/fasta_files_filtered"
fastani: "../tests/results/fastani"
fastani_thresh: 99
contig_db: "../tests/results/contig_dbs"
annotations: "../tests/results/Annotations"
faas: "../tests/results/FAAs"
gene_calls: "../tests/results/GeneCalls"
gff_final: "../tests/results/GFF3-Final"

# Databases
cazyme_db: "dbs/CAZyme/"
cazyme_mapper: "/depot/lindems/data/Databases/CAZyme/fam-substrate-mapping-08252022.tsv"
tigrfam_db: "/depot/lindems/data/Databases/TIGRFams/AllTigrHmms.hmm"
tigrfam_roles: "/depot/lindems/data/Databases/TIGRFams/TFAM-Roles.txt"

# Global Resources
ram_limit: 16
threads: 20

# Logging
log_folder: "logs"
log_id: "Default000"
database_name: "DEFAULT Database Name"

