analysis: 'Metagenomic'

# File Specifications
contigs: "fasta_files"
extension: "fasta"
verified_contigs: "fasta_files_verified"
contig_db: "contig_dbs"

# Databases
cazyme_db: ""
tigrfam_db: ""

# Computing
threads: 80

# Logging
log_id: "AnnotatingMAGs"
